#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Temporarily disabling a systemd timer..."

ynh_systemctl --service="$app-restart.timer" --action="stop"

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
ynh_script_progression "Fetching, starting and customizing initial container..."

ynh_exec_as_app "$install_dir/manage.sh" clear
ynh_exec_as_app "$install_dir/manage.sh" initialize

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

etc_hosts_clear
etc_hosts_add

ynh_config_change_url_nginx

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Enabling the regular restart service..."

systemctl enable "$app-restart.timer" --now --quiet

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
