#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL INCUS
#=================================================
ynh_script_progression "Installing Incus... (this make take a long time!)"

if ! yunohost app list --output-as json --quiet | jq -e '.apps[] | select(.id == "incus")' >/dev/null; then
    yunohost app install --force incus -a cluster=no
fi

setup_incus

usermod -a -G incus "$app"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding app's script..."

ynh_config_add --template="manage.sh" --destination="$install_dir/manage.sh"
chmod 711 "$install_dir/manage.sh"
chown "$app:$app" "$install_dir/manage.sh"

#=================================================
# START CONTAINER
#=================================================
ynh_script_progression "Fetching, starting and customizing initial container..."

ynh_exec_as_app "$install_dir/manage.sh" start
etc_hosts_add

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

etc_hosts_add

ynh_config_add_nginx

# ynh_config_add_systemd

# yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

ynh_config_add --template="sysctl.conf" --destination="/etc/sysctl.d/$app.conf"

# ynh_systemd_action --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
