#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL INCUS
#=================================================
ynh_script_progression "Installing Incus... (this make take a long time!)"

if ! yunohost app list --output-as json --quiet | jq -e '.apps[] | select(.id == "incus")' >/dev/null; then
    yunohost app install --force incus -a cluster=no
fi

setup_incus

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding app's script..."

ynh_config_add --template="manage.sh" --destination="$install_dir/manage.sh"
chmod 711 "$install_dir/manage.sh"
chown "$app:$app" "$install_dir/manage.sh"

#=================================================
# START CONTAINER
#=================================================
ynh_script_progression "Fetching, starting and customizing initial container..."

ynh_exec_as_app "$install_dir/manage.sh" initialize

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

etc_hosts_add

ynh_config_add_nginx

# don't use the helpers because the service has a custom name and workflow
ynh_config_add --template="systemd.timer" --destination="/etc/systemd/system/$app-restart.timer"
ynh_config_add --template="systemd.service" --destination="/etc/systemd/system/$app-restart.service"
systemctl daemon-reload

ynh_config_add_logrotate

ynh_config_add --template="sysctl.conf" --destination="/etc/sysctl.d/$app.conf"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Enabling the regular restart service..."

systemctl enable "$app-restart.timer" --now --quiet

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
