#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL INCUS
#=================================================
ynh_script_progression --message="Installing Incus... (this make take a long time!)"

if ! yunohost app list --output-as json --quiet | jq -e '.apps[] | select(.id == "incus")' >/dev/null; then
    yunohost app install --force incus
fi

setup_incus

usermod -a -G incus "$app"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Fetchin LXC container..."

start_instance

container_ip="$(get_instance_ipv4)"
ynh_app_setting_set --key=container_ip --value="$container_ip"

#=================================================
# ADD A CONFIGURATION
#=================================================
# ynh_script_progression "Adding app's configuration..."

# ynh_exec_as_app mkdir "$install_dir/.ssh"
# ynh_config_add --template="ssh_config" --destination="$install_dir/.ssh/config"
# chmod 400 "$install_dir/"
# chown "$app:$app" "$install_dir/"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

# ynh_config_add_systemd

# yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

ynh_config_add --template="sysctl.conf" --destination="/etc/sysctl.d/$app.conf"

#=================================================
# START SYSTEMD SERVICE
#=================================================
# ynh_script_progression "Starting app's systemd service..."

# ynh_systemd_action --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
