#!/bin/bash
### App file generated with YoloGen, the YunoHost app generator, version .

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_logrotate

ynh_safe_rm "/etc/systemd/system/$app.timer"
ynh_config_remove_systemd

ynh_exec_as_app "$install_dir/manage.sh" stop

ynh_config_remove_nginx

ynh_safe_rm "/etc/sysctl.d/$app.conf"

etc_hosts_clear

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
