#!/bin/bash
### App file generated with YoloGen, the YunoHost app generator, version .

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
# ynh_script_progression "Stopping a systemd service..."

# ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Fetchin LXC container..."

remove_instance
start_instance

container_ip="$(get_instance_ipv4)"
ynh_app_setting_set --key=container_ip --value="$container_ip"

customize_instance

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

# ynh_config_add_systemd

# yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

ynh_config_add --template="sysctl.conf" --destination="/etc/sysctl.d/$app.conf"

#=================================================
# START SYSTEMD SERVICE
#=================================================
# ynh_script_progression "Starting a systemd service..."

# ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
