#!/bin/bash
### App file generated with YoloGen, the YunoHost app generator, version .

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
# ynh_script_progression "Stopping a systemd service..."

# ynh_systemctl --service="$app" --action="stop"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding app's script..."

ynh_config_add --template="manage.sh" --destination="$install_dir/manage.sh"
chmod 711 "$install_dir/manage.sh"
chown "$app:$app" "$install_dir/manage.sh"

#=================================================
# START CONTAINER
#=================================================
ynh_script_progression "Fetching, starting and customizing initial container..."

ynh_exec_as_app "$install_dir/manage.sh" clear
ynh_exec_as_app "$install_dir/manage.sh" initialize
etc_hosts_clear
etc_hosts_add

# ynh_systemd_action --service="$app" --action="start"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

etc_hosts_add

ynh_config_add_nginx

# ynh_config_add_systemd

# yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

ynh_config_add --template="sysctl.conf" --destination="/etc/sysctl.d/$app.conf"

#=================================================
# START SYSTEMD SERVICE
#=================================================
# ynh_script_progression "Starting a systemd service..."

# ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
